#!/bin/bash

# Copyright 2013 The Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

if [ $# -lt 1 -o $# -gt 2 ] ; then
	echo "Usage: $0 [-R] <cmd>"
	exit 1
fi

function loop-recursive {
        for f in ./* ; do
                if [ -d $f ] ; then
                        cd $f
                        $1
                        loop-recursive $1;
                        cd ..
                fi
        done
}

if [ $# -eq 2 ] ; then
	if [ $1 != '-R' ] ; then
		echo "Usage: $0 [-R] <cmd>"
	        exit 1
	fi	
	loop-recursive $2;
else
	for f in ./* ; do
		if [ -d $f ] ; then
			cd $f
			$2
			cd ..
		fi
	done
fi
