#!/bin/bash

function usage {
	echo "Usage: $0 [-R] <cmd> [<dir>]"
	exit 1
}

if [ $# -lt 1 -o $# -gt 3 ] ; then
	usage
fi

RECURSE=
DIR=.
CMD=
PWD=$(pwd)
if [ $# -eq 1 ] ; then
	CMD=$1
elif [ $# -eq 2 ] ; then
	if [ $1 == '-R' ] ; then
		RECURSE='y'
		CMD=$2
	else
		CMD=$1
		DIR=$2
	fi
elif [ $# -eq 3 ] ; then
	if [ $1 != '-R' ] ; then
		usage
	fi
	RECURSE='y'
	CMD=$2
	DIR=$3
fi

function loop-recursive {
        for f in ./* ; do
                if [ -d $f ] ; then
                        cd $f
                        eval $@	# Use $@ instead of $1 in case command has spaces
                        loop-recursive $@;
                        cd ..
                fi
        done
}

cd $DIR
if [ $RECURSE ] ; then
	loop-recursive $CMD
else
	for f in ./* ; do
		if [ -d $f ] ; then
			cd $f
			eval $CMD
			cd ..
		fi
	done
fi
cd $PWD
